# Generated by Django 2.2.1 on 2019-06-03 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='billing_prodile',
            new_name='billing_profile',
        ),
    ]
