# Generated by Django 2.2.1 on 2019-06-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_auto_20190603_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charge',
            old_name='billling_profile',
            new_name='billing_profile',
        ),
    ]
