# Generated by Django 2.1 on 2019-06-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpreference',
            name='mailchimp_subscribed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='marketingpreference',
            name='subscribed',
            field=models.NullBooleanField(),
        ),
    ]
