# Generated by Django 2.2.1 on 2019-05-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190519_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_adress',
            new_name='billing_address',
        ),
    ]
